version: "3.3"
services:
  registry-service:
    image: evgeny88docker/registry-service:1.0
    build:
      context: ./SmallMarketPlaceServiceRegistry
      dockerfile: Dockerfile
    container_name: registry-service
    ports:
      - "8761:8761"
    restart: always
    networks:
      - proxynet

networks:
  proxynet:
    external:
      name: smallmarketplace_proxynet

