server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: ItemStorage-Service
          uri: lb://ItemStorage-Service
          predicates:
            - Path=/itemstorage/**
          filters:
            - name: CircuitBreaker
              args:
                name: itemStorageCircuitBreaker
                fallbackUri: forward:/fallback-for-itemStorageService
        - id: SaleOrders-Service
          uri: lb://SaleOrders-Service
          predicates:
            - Path=/saleorders/**
          filters:
            - name: CircuitBreaker
              args:
                name: saleOrdersCircuitBreaker
                fallbackUri: forward:/fallback-for-saleOrdersService

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  instance:
    prefer-ip-address: true
    hostname: registry-0
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://${eureka.instance.hostname}.registry.default.svc.cluster.local:8761/eureka
