server:
  port: 8080
spring:
  application:
    name: ApiGateway-Service
  cloud:
    gateway:
      routes:
        - id: ItemStorage-Service
          uri: lb://ItemStorage-Service
          predicates:
            - Path=/itemstorage/**
          filter:
            - name: circuitBreaker
              args:
                name: ItemStorage-Service
                fallbackUri: http://localhost:8080/itemstorage/api/v1/*/fallback-for-itemStorageService
        - id: SaleOrders-Service
          uri: lb://SaleOrders-Service
          predicates:
            - Path=/saleorders/**
          filter:
            - name: circuitBreaker
              args:
                name: SaleOrders-Service
                fallbackUri: forward:/fallback-for-saleOrdersService

#hystrix:
#  metrics:
#    polling-interval-ms: 4000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    hystrix:
      stream:
        enabled: true
