version: "3.3"
services:
  itemstorageDB:
    image: postgres:13
    container_name: itemstorageDB
    environment:
      POSTGRES_PASSWORD: Primera77!
      POSTGRES_USER: evgeny88
      POSTGRES_DB: itemstorage
      POSTGRES_HOST: itemstorageDB
    ports:
      - "5433:5432"
    restart: always
    networks:
      - proxynet

  saleordersDB:
    image: postgres:13
    container_name: saleordersDB
    environment:
      POSTGRES_PASSWORD: Primera77!
      POSTGRES_USER: evgeny88
      POSTGRES_DB: saleorders
      POSTGRES_HOST: saleordersDB
    ports:
      - "5434:5432"
    restart: always
    networks:
      - proxynet
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - proxynet
      
  kafka:
    image: confluentinc/cp-kafka:7.0.0
    container_name: kafka-broker
    ports:
      - "9092:9092"
    expose:
      - "29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - proxynet

  redis:
    image: redis
    container_name: redis_cache
    hostname: redishost
    ports:
      - "6379:6379"
    expose:
      - "6379"
    command: redis-server --requirepass Primera77!
    restart: always
    environment:
      REDIS_PORT_NUMBER: 6379
      REDIS_USER: evgeny88
      REDIS_PASSWORD: Primera77!
      REDIS_REPLICATION_MODE: master
    networks:
      - proxynet

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin-server
    ports:
      - "9411:9411"
    expose:
      - "9411"
    networks:
      - proxynet

networks:
  proxynet:
