apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: "confluentinc/cp-kafka:7.0.0"
          imagePullPolicy: IfNotPresent
          name: kafka-container
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "LISTENER_1:PLAINTEXT,LISTENER_2:PLAINTEXT"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: "LISTENER_1://:30092,LISTENER_2://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "LISTENER_1://:30092,LISTENER_2://:9092"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "LISTENER_2"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper-service:2181"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
spec:
  type: ClusterIP
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
      protocol: TCP
  selector:
    app: kafka

#bitnami/kafka:latest"
