apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-cm
data:
  eureka_service_address: http://localhost:8761/eureka

---

apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    app: registry
spec:
  clusterIP: None
  ports:
    - port: 8761
  selector:
    app: registry

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
spec:
  serviceName: "registry"
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
        - name: registry-service
          image: evgeny88docker/registry-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: registry-cm
                  key: eureka_service_address

---

apiVersion: v1
kind: Service
metadata:
  name: registry-lb
  labels:
    app: registry
spec:
  selector:
    app: registry
  type: NodePort
  ports:
    - port: 80
      targetPort: 8761
