apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleorders-service
  labels:
    app: saleorders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: saleorders-service
  template:
    metadata:
      labels:
        app: saleorders-service
    spec:
      containers:
        - name: saleorders-service
          image: evgeny88docker/saleorders-service:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8082

---

apiVersion: v1
kind: Service
metadata:
  name: saleorders-service
spec:
  ports:
    - targetPort: 8082
      port: 80
  selector:
    app: saleorders-service