apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: "confluentinc/cp-kafka:7.0.0"
          imagePullPolicy: IfNotPresent
          name: kafka-container
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:30092"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181/30181"
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
spec:
  type: NodePort
  ports:
    - name: kafka-port
      port: 9092
      nodePort: 30092
      targetPort: 9092
  selector:
    app: kafka
