apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: "confluentinc/cp-kafka:7.0.0"
          imagePullPolicy: IfNotPresent
          name: kafka-container
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_BSTR
              valueFrom:
                  configMapKeyRef:
                    name: kafka-maps
                    key: KAFKA_BOOTSTRAP
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: "HOST:PLAINTEXT"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_LISTENERS
              value: "HOST://$(KAFKA_BSTR)"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "HOST://$(KAFKA_BSTR)"
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: "HOST"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "zookeeper:2181"

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-service
  name: kafka-service
spec:
  type: ClusterIP
  ports:
    - name: kafka-port
      port: 9092
      targetPort: 9092
  selector:
    app: kafka
