### get all dto items
GET http://localhost:8080/itemstorage/api/v1/itemsDTO
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

### get itemDTO by parent id
GET http://localhost:8080/itemstorage/api/v1/itemsDTO/9
Accept: */*
Content-Type: application/json
Cache-Control: no-cache

#### connection with kafka console-consumer:
#kafka-console-producer --bootstrap-server localhost:9092 --topic mytopic